apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
spec:
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: flasktest
        image: public.ecr.aws/c3w1m1q2/frontend-st:latest
        ports:
        - containerPort: 3000
  replicas: 2

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-swapna-Mern-service
spec:
  selector:
    app: frontend-swapna-Mern
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
